# vim:set ft=tmux:

# --> Catppuccin (Onedark)
set -ogq @thm_bg "#282c34"
set -ogq @thm_fg "#abb2bf"

# Colors
set -ogq @thm_rosewater "#e8b4a8"
set -ogq @thm_flamingo "#e5989b"
set -ogq @thm_pink "#e06c75"
set -ogq @thm_mauve "#c678dd"
set -ogq @thm_red "#be5046"
set -ogq @thm_maroon "#d16969"
set -ogq @thm_peach "#d19a66"
set -ogq @thm_yellow "#e5c07b"
set -ogq @thm_green "#98c379"
set -ogq @thm_teal "#56b6c2"
set -ogq @thm_sky "#6cb6c9"
set -ogq @thm_sapphire "#61afef"
set -ogq @thm_blue "#528bff"
set -ogq @thm_lavender "#a9b1f7"

# Surfaces and overlays
set -ogq @thm_subtext_1 "#9da5b4"
set -ogq @thm_subtext_0 "#8f98a8"
set -ogq @thm_overlay_2 "#828997"
set -ogq @thm_overlay_1 "#747c8c"
set -ogq @thm_overlay_0 "#666e7e"
set -ogq @thm_surface_2 "#5c6370"
set -ogq @thm_surface_1 "#4b5263"
set -ogq @thm_surface_0 "#3d424b"
set -ogq @thm_mantle "#21252b"
set -ogq @thm_crust "#1b1e23"
